export type RehearsalSession = {
  playbookId: string;
  roleId: string;
  lineIndex: number;
  cueDepth: number;
  includeDirections: boolean;
  includeBlocking?: boolean;
  blockingScope?: "role" | "all";
  revealLine: boolean;
  showLinesByDefault: boolean;
  cueWindowPresetId: string;
  playbackRate: number;
  speakAlongEnabled: boolean;
  speakAlongPauseMs: number;
  tempoTargetHesitationMs: number;
  practiceTargetPaceMultiplier?: number;
  syncSpeakAlongSpeed?: boolean;
  absoluteTempoForgivenessMs?: number;
  absolutePickupForgivenessMs?: number;
  tempoTolerancePercent?: number;
  syncPracticeTiming: boolean;
  tempoTimingPreferred: boolean;
  rehearsalTextSize?: "small" | "medium" | "large" | "x-large";
  updatedAt: number;
};
