export type RecordingItem = {
  lineId: string;
  blockId: string;
  segmentId: string;
  sequence: number;
  displayText: string;
  segmentText: string;
  outputPath: string;
  cueText?: string;
  cueSpeaker?: string;
  previousText?: string;
  previousSpeaker?: string;
  nextText?: string;
  nextSpeaker?: string;
  sectionId?: string;
  sectionTitle?: string;
  sceneHeading?: string;
  stageDirections: string[];
  reason?: string;
  notes?: string;
  changed?: boolean;
  cueAudio?: string;
  previousRecording?: string;
  targetDurationMs?: number;
  targetHesitationMs?: number;
  simultaneous?: boolean;
};
